FROM odoo:17.0

USER root
RUN pip3 install --no-cache-dir \
    pandas \
    numpy \
    scipy \
    kafka-python-ng \
    requests \
    opencv-python-headless \
    rapidocr_onnxruntime \
    pypdf

USER odoo
